<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="669" started-at="2014-04-19T18:20:12Z" finished-at="2014-04-19T18:20:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="669" started-at="2014-04-19T18:20:12Z" finished-at="2014-04-19T18:20:13Z">
      <class name="com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest@cb644e]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="14" started-at="2014-04-19T20:20:12Z" finished-at="2014-04-19T20:20:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest@cb644e]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="615" started-at="2014-04-19T20:20:12Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2014-04-19T20:20:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest@cb644e]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="1" started-at="2014-04-19T20:20:13Z" finished-at="2014-04-19T20:20:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest.testGetCV() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="FAIL" signature="testGetCV()[pri:0, instance:com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest@cb644e]" name="testGetCV" duration-ms="10" started-at="2014-04-19T20:20:13Z" finished-at="2014-04-19T20:20:13Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: class path resource [data/tomas-skalicky-cv-en.json] cannot be opened because it does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: class path resource [data/tomas-skalicky-cv-en.json] cannot be opened because it does not exist
	at com.skalicky.tomas.cv.businesslogic.CVServiceImpl.getCV(CVServiceImpl.java:43)
	at com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest.testGetCV(CVServiceImplIntegrationalTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.io.FileNotFoundException: class path resource [data/tomas-skalicky-cv-en.json] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:158)
	at com.skalicky.tomas.cv.businesslogic.CVServiceImpl.getCVResource(CVServiceImpl.java:51)
	at com.skalicky.tomas.cv.businesslogic.CVServiceImpl.getCV(CVServiceImpl.java:38)
	... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCV -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest@cb644e]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="4" started-at="2014-04-19T20:20:13Z" finished-at="2014-04-19T20:20:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest.testGetCV() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest@cb644e]" name="springTestContextAfterTestClass" is-config="true" duration-ms="1" started-at="2014-04-19T20:20:13Z" finished-at="2014-04-19T20:20:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- com.skalicky.tomas.cv.businesslogic.CVServiceImplIntegrationalTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
